class TEMPERATURE_SET_DEFAULT:
    ALARM_MAX = 75
    ALARM_MIN = 0
    WARN_MAX = 65
    WARN_MIN = 0


class VIBRATION_SET_DEFAULT:
    ALARM_MAX = 7.099999904632568
    ALARM_MIN = 0
    WARN_MAX = 4.5
    WARN_MIN = 0


class COOLER_SET_DEFAULT:
    WATER_BEFOR_ALERT_MAX = 30
    WATER_AFTER_ALERT_MAX = 30
    OIL_BEFOR_ALERT_MAX = 30
    OIL_AFTER_ALERT_MAX = 30
