version: "3"

services:
  backend:
    build:
      context: ../
      dockerfile: deployment/exhauster_backend/Dockerfile
    restart: always
    entrypoint: entrypoint_api.sh
    environment:
      - DATABASE_USER=hackaton_backend
      - DATABASE_PASSWORD=
      - DATABASE_HOST=hackaton-postgres-do-user-13570410-0.b.db.ondigitalocean.com
      - DATABASE_PORT=25060
      - DATABASE_NAME=hackaton-dev
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - BROKER_USER=admin
      - BROKER_PASS=
      - API_PORT=8000
      - API_LOG_LEVEL=debug
      - SWAGGER_ON=true
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_healthy

  # frontend:

  rabbitmq:
    image: pcloud/rabbitmq-stomp:3.9
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613