"""change shema

Revision ID: 877eddc3b3ac
Revises: 18f540a9566c
Create Date: 2023-02-19 01:07:12.594302+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877eddc3b3ac'
down_revision = '18f540a9566c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotors', sa.Column('installed_at', sa.DateTime(), nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rotors', 'installed_at', schema='app')
    # ### end Alembic commands ###
