"""mod

Revision ID: 0b1b1e0625cf
Revises: 510ad9936a96
Create Date: 2023-02-18 14:25:15.757617+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b1b1e0625cf'
down_revision = '510ad9936a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'exhausters',
        sa.Column('aglomachine', sa.String(length=255), nullable=True),
        schema='app'
    )
    op.drop_column('exhausters', 'is_active', schema='app')
    op.add_column(
        'rotors',
        sa.Column('exhauster_id', sa.Integer(), nullable=True),
        schema='app'
    )
    op.add_column(
        'rotors',
        sa.Column('installed_at', sa.DateTime(), nullable=False),
        schema='app'
    )
    op.create_foreign_key(
        op.f('fk_rotors_exhauster_id_exhausters'),
        'rotors',
        'exhausters', ['exhauster_id'], ['id'],
        source_schema='app',
        referent_schema='app'
    )
    op.add_column(
        'rotors_prediction',
        sa.Column('exhauster_id', sa.Integer(), nullable=True),
        schema='app'
    )
    op.create_foreign_key(
        op.f('fk_rotors_prediction_exhauster_id_exhausters'),
        'rotors_prediction',
        'exhausters', ['exhauster_id'], ['id'],
        source_schema='app',
        referent_schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_rotors_prediction_exhauster_id_exhausters'),
        'rotors_prediction',
        schema='app',
        type_='foreignkey'
    )
    op.drop_column('rotors_prediction', 'exhauster_id', schema='app')
    op.drop_constraint(
        op.f('fk_rotors_exhauster_id_exhausters'),
        'rotors',
        schema='app',
        type_='foreignkey'
    )
    op.drop_column('rotors', 'exhauster_id', schema='app')
    op.add_column(
        'exhausters',
        sa.Column(
            'is_active', sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        schema='app'
    )
    op.drop_column('exhausters', 'aglomachine', schema='app')
    # ### end Alembic commands ###
